fixtures:
    symlinks:
      gitlab_ci_multi_runner: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.9.0
      archive: git@gitlab.com:singlestone/puppet-archive.git

    forge_modules:
